host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pip-tools

runtime_environments:
  - name: ubi8
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.6"
    recommendation_type: stable

  - name: f32
    operating_system:
      name: fedora
      version: "32"
    python_version: "3.7"
    recommendation_type: stable
